### ISSUE TITLE
License

### ISSUE THREAD

**Issue by chupAkabRRa** [eXiga/ConfreaksMTV#2]
First things first in the open source world - license. I guess MIT is ok. Up to you. Place the text within README file then. Have you seen [this repo](https://github.com/cabaret/confreaks-react-native)? Looks like it's dead in the very beginning. But I like the number of Stars for almost empty repo:)

**Comment by eXiga** [comment]
@chupAkabRRa done with license. You can look at this [commit](https://github.com/eXiga/ConfreaksMTV/commit/592bd42f6e47a9d71cb3f761a660716dd99657ec)
